baseurl = "https://mlenoir.com"
title = "Devoted Husband | Tired Father of 3"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "kksudo"
enableGitInfo = true
enableRobotsTXT = true

# Hugo settings
[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[params]
author = "Matthew LeNoir"
info = ["Doin Stuff"]
description = "Matthew's personal page"
keywords = "blog,businesscard,personal,devops,"
gravatar = "matthewlenoir56@gmail.com"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon.png"

since = 2010
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/kksudo/kazakov.xyz/tree/"
powered_by = true
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
#tag = "tags"
#author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/mlenoir919/"
target = "_blank"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://www.instagram.com/matteo_knows/"
target = "_blank"
[[params.social]]
name = "spam@mlenoir.com"
icon = "fa fa-envelope fa-2x"
weight = 6
url = "mailto:spam@mlenoir.com"
target = "_blank"

# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"


